name: deploy

on:
  # Trigger the workflow on push to main branch with changes
  push:
    branches:
    - main

permissions:
  pages: write
  deployments: write
  contents: write
  statuses: write
  actions: write
  checks: read

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - uses: prefix-dev/setup-pixi@v0.8.0
      with:
        pixi-version: latest
        cache: true

    # Build the book
    - name: Build the book
      run: pixi run build-book

    # Deploy the book's HTML to gh-pages branch
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: open-tyndp-workshops/_build/html
