name: deploy PR previews

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - closed

concurrency: preview-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-preview-book:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - uses: prefix-dev/setup-pixi@v0.8.0
      with:
        pixi-version: latest
        cache: true

    - name: Install pixi
      run: |
        curl -fsSL https://pixi.sh/install.sh | sh
        echo "$HOME/.pixi/bin" >> "$GITHUB_PATH"
        export PATH="$HOME/.pixi/bin:$PATH"
        pixi --version

    # Build the book
    - name: Build the book
      run: pixi run build-book

    # Deploy the preview
    - name: Deploy preview
      uses: rossjrw/pr-preview-action@v1
      with:
        source-dir: open-tyndp-workshops/_build/html
